### ISSUE TITLE
dns: specify nameserver

### ISSUE THREAD

**Issue by albertrdixon** [aelsabbahy/goss#141]
Would be great if I could specify the nameserver (e.g. `8.8.8.8`) to use for the dns check.

**Comment by aelsabbahy** [comment]
Agree, would be a good feature.

**Comment by pysysops** [comment]
I don't mind submitting a PR for this, it will probably require using github.com/miekg/dns instead of the net package. I'd also like to add an enhancement to the DNS resource: a type attribute to specify the Record type (TXT, PTR, CNAME, SRV, SPF for example). I would be more than happy to close PR #143 for reverse-dns resource and work it into the dns resource?

DNS is often one of the most problematic / forgotten things. Been able to test / validate DNS as part of a CI / CD or monitoring pipeline is awesome.

**Comment by aelsabbahy** [comment]
@pysysops Yeah, when I saw this issue I was looking at `miekg/dns` since it doesn't seem like the built in `net` supports this.

If it's not too much trouble, I would love to see your proposed syntax for #143 + this feature. I'm okay with `dns` being a catchall so long as it's not too cluttered or confusing to the end user.

Many thanks for your contributions so far :+1:

**Comment by aelsabbahy** [comment]
@pysysops Just a heads up, if you think this DNS change will be done before the end of the week, I'll hold off and cut a release then. Otherwise I might cut a goss release tomorrow with some small bug fixes.

**Comment by pysysops** [comment]
I'll put a bit of time in and try to get it in by Friday. I'll let you know if things don't go to plan on Thursday. Thanks!

**Comment by pysysops** [comment]
Feel free to cut a release without this enhancement, my time has been consumed by some major project work for a client this week...  

Thanks,
Tim

**Comment by pysysops** [comment]
Finally managed to put a little time into working something out for this in PR #170

**Comment by pysysops** [comment]
@aelsabbahy think you can close this off 😄
