### ISSUE TITLE
Test port on an external system

### ISSUE THREAD

**Issue by CMeza99** [aelsabbahy/goss#161]
I would like a netcat and ping like functionality so I can test if I can reach another system's ports, check the banner, or test via ICMP.

**Comment by aelsabbahy** [comment]
There's already support for remote port:
```yaml
addr:
  tcp://google.com:443:
    reachable: true
    timeout: 500
```

I'm on the fence for netcat like functionality, since it raises a lot of questions, how much should you read from the remote address before stopping, do you need to send things to the remote address before you get the proper header, etc.

Gonna have to think about this feature a bit and whether it's something that should be added to goss, or just left to the user to handle in `command`

**Comment by CMeza99** [comment]
Oh. I missed that there was this feature was implemented. The main functionality is there, is the port reachable, so even to consider this should be a low priority.

**Comment by aelsabbahy** [comment]
Gonna close this out for now.. if anyone feels strongly about this, feel free to reopen.
