### ISSUE TITLE
Packages not reporting enabled correctly on centos

### ISSUE THREAD

**Issue by cagedmantis** [aelsabbahy/goss#162]
After removing packages a service test will report that a service is enabled when it is not.  I've tested with this Centos 6 and Centos 7.

**Comment by aelsabbahy** [comment]
What does `service` or `systemctl` report for the service?

For centos6 it'll be checking the init file exists for that service:
https://github.com/aelsabbahy/goss/blob/caf16b35d9d88a491f30f2a4b9d81785b3d1cbdf/system/service_init.go#L62-L66

Is there a `/etc/rc3.d/S*$SERVICE_NAME` file on your filesystem?

For systemctl it checks `systemctl -q is-enabled $SERVICE_NAME` and falls back on the check above (since some systems are hybrid systemctl + sysv):
https://github.com/aelsabbahy/goss/blob/caf16b35d9d88a491f30f2a4b9d81785b3d1cbdf/system/service_systemd.go#L45-L55

**Comment by cagedmantis** [comment]
On Centos 7. Service `grip` has been removed via `yum remove grip`

I use a goss.yaml file to validate:
`service:
  grip:
    enabled: false
    running: false`

After a `goss validate` the output is:
`Service: grip: enabled:
Expected
    <bool>: true
to equal
    <bool>: false`

And then, I found lingering files in `/etc/rc.d/*`
Thanks for helping me debug. I believe I found the issue. The problem exists elsewhere.

**Comment by aelsabbahy** [comment]
No problem, thanks for using goss =)
