### ISSUE TITLE
Let filetype accept the string "folder" too.

### ISSUE THREAD

**Issue by lowks** [aelsabbahy/goss#165]
Now goss when checking for folder expects:

`"filetype": "directory",`

Can you extend this to accept either `folder` or `directory` ?

**Comment by aelsabbahy** [comment]
Is this just a preference thing, or is there a technical reason? (curious)

**Comment by lowks** [comment]
I tried the first time to put folder and saw it only accept folder. Both of them are the same thing no ?

The Lowkster

Sent from
https://polymail.io/?utm_source=polymail&utm_medium=referral&utm_campaign=signature

On Wed, 19 Oct 2016 at 9:15 PM Ahmed Elsabbahy

<
mailto:Ahmed Elsabbahy <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Is this just a preference thing, or is there a technical reason? (curious)

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/aelsabbahy/goss/issues/165#issuecomment-254808844
, or

**Comment by aelsabbahy** [comment]
Sorry I could have sworn I responded to this 2 days ago, guess I forgot to hit submit.

Basically the way goss works is by comparing the result of the "system resource" with the defined "test resource". It's currently a simple match without the concept of aliases or alternate values.

I hesitate to add this since it would be the only exception in the test framework. That said, if more cases like this come up, then I'll reconsider adding this feature.

**Comment by aelsabbahy** [comment]
Gonna close this for now, if another case like this pops up, I'll reopen.
