### ISSUE TITLE
Remote validations

### ISSUE THREAD

**Issue by mongrelion** [aelsabbahy/goss#208]
Installing the goss binary in thousands of production machines is a no go for lost of companies out there. Is it possible to run the tests by connecting to a remote machine?

**Comment by aelsabbahy** [comment]
See my notes on remote execution from my year ago: https://github.com/aelsabbahy/goss/issues/6#issuecomment-151610078

You can use a tool like [ansible](https://github.com/ansible/ansible) + [degoss role](https://github.com/naftulikay/ansible-role-degoss) to automate this, or roll your own. Since it's a standalone binary, it's pretty simple to install/remove from a machine. 

If I had to explain it in code, it would be something like this:
```
ssh remote_host '
curl -L https://github.com/aelsabbahy/goss/releases/download/v0.3.1/goss-linux-amd64 -o /tmp/goss && \
chmod 755 /tmp/goss && \
/tmp/goss -g - validate;ret=$?
rm -f /tmp/goss;exit $ret' < goss.yaml
```

**Comment by aelsabbahy** [comment]
Feel free to re-open if you have follow up questions.

**Comment by mongrelion** [comment]
Thanks for your answer. Somehow I missed it.
Indeed, using something like Ansible will make it easy to install the goss binary, push the configuration and run the tests.
However, this still requires goss to be installed on the machines.
I guess what I want is fundamentally different to how goss is built.

Thanks again.

**Comment by q2dg** [comment]
Maybe https://github.com/teuton-software/teuton can help
