### ISSUE TITLE
User friendly output for failed "command".

### ISSUE THREAD

**Issue by taurus-forever** [aelsabbahy/goss#213]
Hi,
I am not a native speaker, while every time I spend ~10 seconds to understand what I have received here:
```
> Command: getent passwd superman: exit-status:
> Expected
>     <int>: 0
> to equal
>     <int>: 2
```

Can it be mode user friendly? Like:

```
> Command: getent passwd superman: exit-status:
> Received:  <int>: 2
> Expected:  <int>: 0
```
or
```
> Command: getent passwd superman: exit-status: <int>: 2
> Expected:  <int>: 0
```
or
```
> Command: getent passwd superman
> Exit-status: <int>: 2
> Expected:  <int>: 0
```
Sure, maybe it is my lonely problems, feel free to resolve the ticket then!

**Comment by aelsabbahy** [comment]
Nah, it's not just you. I often have to double read the test results myself.

So, that output comes from the gomega matchers. To change it I would have to extend them locally in Goss. Which might not be a bad idea, since Goss only uses a subset anyways.

I'll keep this open as an enhancement request.

**Comment by kurt---** [comment]
+1 for this feature request

Am 24.03.2017 1:46 PM schrieb "Ahmed Elsabbahy" <notifications@github.com>:

**Comment by aelsabbahy** [comment]
Closing this for now. There's a gomega issue tracking this, see my comment here:
https://github.com/aelsabbahy/goss/issues/453#issuecomment-564866168
