### ISSUE TITLE
No license for github.com/aelsabbahy/GOnetstat

### ISSUE THREAD

**Issue by andrewsomething** [aelsabbahy/goss#23]
First of all, thanks for building goss. I really love the simplicity of generating the "tests" from a known good system. In fact, I'm hoping to package it for Debian. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=804202

Though, I've hit a bit of a snag. `github.com/aelsabbahy/GOnetstat` doesn't have any license information, and niether does the project it was forked from. I opened an issue about this on https://github.com/drael/GOnetstat/issues/1, but that porject hasn't seen much activity in sometime now.

Unfortunately, this blocks distributing it in Debian (and presumably other distros).

I'm opening this to track the issue and start a conversation. I haven't looked too closely at whether there are other libraries providing similar functionality or not yet. Worst case, I might attempt a clean room reimplementation.

**Comment by aelsabbahy** [comment]
GOnetstat is a pretty simple, so a re-implementation might not be a bad idea. I mostly bring this up because the project I forked hasn't been active for two years.

Unfortunately, I'm currently in the middle of a job transition and haven't had much free time to invest in `goss`. I'm hoping as the dust settles on my transition (probably holiday season) that I'm able to dedicate more time to the project.

In case you (or someone else) decides to take this issue on, the main reason I forked GoNetstat is for performance:
* Pid lookups are slow, I made this optional and kept it disabled when validating
* Pid lookup is still needed since it's used by `goss autoadd` to lookup all ports related to a process
* Modified Pid lookups to be quicker by dropping regex. Not sure this is a big deal, since it'ls only used when doing `goss autoadd` and I'm not too concerned about the performance of that operation
* A solution must not rely on system commands or use a solution that relies on one. ex: [shirou/gopsutil](https://github.com/shirou/gopsutil) relies on `lsof` being on the system.


Thank you for looking into packaging goss the tool is intended to be stupid-simple to get started with and use.. native packages goes a long way in making that possible.

**Comment by andrewsomething** [comment]
The original author has now indicated that it is indeed licensed under the MIT:

https://github.com/drael/GOnetstat/commit/a08125f5157d481dd0d0355c021467bd8c84eb6d

**Comment by aelsabbahy** [comment]
Aside from adding the license to my forked version is there anything else I need to do for this issue?

**Comment by andrewsomething** [comment]
Thanks should be it. Thanks!

**Comment by aelsabbahy** [comment]
Added at https://github.com/aelsabbahy/GOnetstat/commit/ecc13c5416242c8183ecdba2d79136fbcf7e0268
