### ISSUE TITLE
Allow check to look for either tcp4 or tcp6 port listening

### ISSUE THREAD

**Issue by kwaio** [aelsabbahy/goss#309]
Hi,

A problem we regularily face is that sometimes, depending on software version, OS, OS version, etc. servers listen on ::, sometimes on 0.0.0.0, which makes writing gossfile quite complicated 

(and led us to disable ipv6 on some hosts, which is not a good solution)

Is there any way to write a check that accepts either 0.0.0.0 OR :: ?

**Comment by aelsabbahy** [comment]
1. Love the name.

This issue has been a pain for quite a while. I've been looking for some help on how to handle this, there's an issue open with a more thorough discussion of the problem here https://github.com/aelsabbahy/goss/issues/149

Do you know of any tool that handles this cleanly? If so, please add a comment to issue https://github.com/aelsabbahy/goss/issues/149
