### ISSUE TITLE
Service systemd implementation should not fallback to use sysvinit one

### ISSUE THREAD

**Issue by guillemj** [aelsabbahy/goss#319]
The current service_systemd.go implementation is falling back to use the sysvinit one (service_init.go) when the commands give an error exit core. This is wrong, because systemd should have either generated a service file for those sysvinit init scripts, or it or the admin might have disabled or masked those services, so falling back will give the wrong result. But it will definitely not pay attention to those sysvinit services outside of its compat support anyway, so either systemctl knows about it, or for all practical purposes it does not matter at all.

The case in point here for us, was the motd service, which is masked on Debian, so systemctl is-enabled motd will return an error code, but while having the Debian initscripts package installed, there will be sysvinit enabled service present, so a check expecting the service to be disabled and not running will fail with an unexpected result when it should have succeeded.

**Comment by taurus-forever** [comment]
@aelsabbahy Is it possible to pay attention to the current pull request?
At the moment we have stuck on 0.3.5+patch from pull request,
but we would like to upgrade 0.3.7+ one day.

Our problem is simple: goss doesn't behave well on systemd based servers
where some services are disabled but they are also provide sysvinit scripts.
Race condition happens when we disable/mask such service in
systemd using the standard systemd approaches. In this case goss calls sysvinit scripts.

We need a way to disable fallback to sysvinit if service is masked/disabled in systemd.
The proposed pull request just removes fallback as logically is it wrong, IMHO.
Maybe you are worrying for backward compatibility here, in this case maybe
we can have agree on some goss configuration option which will keep current defaults
but allows us to disable fallback? Tnx!

**Comment by aelsabbahy** [comment]
Sorry for missing this in the last release. I merged the PR into master. Can you confirm that master looks good.

Once we sort out #446 I can cut a new release.

**Comment by aelsabbahy** [comment]
Closing since this is merged/released.
