### ISSUE TITLE
Why goss? :)

### ISSUE THREAD

**Issue by stuckj** [aelsabbahy/goss#33]
This is a trivial question that you can choose to ignore if you wish. But, purely out of curiosity...why is goss named goss? :)

**Comment by stephanbuys** [comment]
Going to guess 'go server spec' :8ball:

**Comment by aelsabbahy** [comment]
Yup, 'go serverspec' because I'm not creative :)

But the name is misleading, since I don't intent for Goss to be a fully-featured serverspec.

Honestly, this started as a pet project to learn go, then it became useful, so I opensourced it. The goal was to have something simple, light and fast for server validation.
