### ISSUE TITLE
Allow serve to re-read goss.yaml to dynamically include newly added tests

### ISSUE THREAD

**Issue by chbndrhnns** [aelsabbahy/goss#331]
Could you please add a command line option so that goss re-reads the goss.yaml file when running in serve mode so that new tests that are added are also executed?
It would help a lot for implementing a test-driven approach to server validation if I could always query the healthpoint and also see newly added tests without having to restart goss.

**Comment by aelsabbahy** [comment]
The challenge would be how to handle added/modified/removed nested goss.yaml's that contain typos or syntax errors. Today goss serve won't start with an invalid config.

**Comment by chbndrhnns** [comment]
What about being in an error state until the syntax errors are solved? Like trying to parse the file(s) when receiving a GET to the health point returning an error ?

**Comment by aelsabbahy** [comment]
I'd have to think about how to make it consistent, some thoughts:

* If the goss.yaml is initially in a bad state, should `goss serve` start up and serve error msg or insta-fail? (the former would be a change in behavior)
* What if the goss.yaml gets in a bad state later due to edits to the goss.yaml
* Should syntax errors be presented in the output format or just a plaintext 503?


The first two bullet points I would want to be consistent. For the interface it would probably be something like `goss serve --live-reload`

In the meantime, I you can probably use a generic livereload tool, some examples:
* https://github.com/cespare/reflex
* https://github.com/cortesi/modd

**Comment by chbndrhnns** [comment]
Another feature I am currently looking at (which is a bit redundant, I guess) is to inject a new goss.yaml via the webserver that goss runs to serve the healthcheck. 

So whenever a POST is received with a valid 'goss.yaml' or an archive that contains multiple yaml files, goss does a live reload.

I am not sure if such a solution would scale if there are lots of checks that are run but I assume it would serve my point to have an instance of goss running and be able to do a live reload.

**Comment by berney** [comment]
Perhaps running goss via S6 and instructing S6 to reload goss (reloading the gossfiles).

**Comment by aelsabbahy** [comment]
I'm going to leave this outside the scope of goss.

@chbndrhnns the POST suggestion sounds cool, but opens up a security risk since Goss runs commands on the host system.
