### ISSUE TITLE
Where is the Docker image?

### ISSUE THREAD

**Issue by stefaniuk** [aelsabbahy/goss#332]
It would be good to be able to run dgoss from another container and not having to install it locally. Any plans to add it?

**Comment by aelsabbahy** [comment]
Just so I'm clear, we're talking about a docker container with goss/dgoss installed + docker binary. This way it can be used to `dgoss` validate other containers? That would be pretty cool.

There's currently a goss docker image, but it doesn't contain the docker CLI. I would be open to pull requests to this [repo](https://github.com/aelsabbahy/goss-docker#mount-example) if you wanna take this on.

![yo-dawg-i-heard-you-like-containers-so-i-put-a-container-in-your-container](https://user-images.githubusercontent.com/6783261/37557088-cd83fc78-29d5-11e8-810a-34430da25863.jpg)

**Comment by plispe** [comment]
I could make a pull request for this, but using dgoss from docker container can lead to very confusing errors, especially for people whose do not know Docker well. Because dgoss mounts or copies testing files and goss utility from host machine into a tested container. if you run dgoss as docker container you have to mount goss test files as volume info container dgoss running in and then into tested container. It could be done with little change in dgoss script, but if you will run dgoss in environment where docker client and docker daemon will be not on the same machine this solution will not work. Overall I think, that running dgoss in container will give you no benefits.

**Comment by aelsabbahy** [comment]
Agree with @plispe if someone wants to do this, there's nothing stopping them.

Closing this out, doesn't seem to have garnered much interest.
