### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by tgeens** [aelsabbahy/goss#357]
This is a very awesome tool! Thank you very much for creating and sharing this!

I'd like to start using goss rather intensively, but I'm a bit worried no PR's have been merged for 5 months.

* Can we get some pointers on the project status and direction ?
* Does the project need help somehow ?

**Comment by aelsabbahy** [comment]
Hi @tgeens , thanks for the inquiry. I've been falling behind on supporting goss due to being very busy. 

Project status/direction:
Bugs:
These are prioritized and fixed, PRs are always welcome for fixing bugs.
I've fallen a bit behind on this and have only been reviewing/merging bugfix PR's but haven't been doing much coding myself. I'll triage and fix any open bug issues in the coming weeks.

Feature requests:
I'm not against features being added to `goss`, however, I don't want goss to grow into an overly complex tool. I take an 80/20 approach to this, Goss should support the 20% and fall back to `command` for anything else.
I merged all the PRs that were ready for merging today, all of them were enhancements. I'll cut a release sometime this week.

Does the project need help somehow ?
Any help is welcome, especially when it comes to PR's with bug fixes.

**Comment by tgeens** [comment]
Thanks for explaining the status and the approach! The project is alive and still improving :-)

I'm planning to stick around for a bit and try to contribute something meaningful. (My 2-character-diff PR is already merged :+1:)
