### ISSUE TITLE
Kubectl Resource

### ISSUE THREAD

**Issue by retr0h** [aelsabbahy/goss#414]
Are there plans to support Kubernetes?  When I initially wrote Molecule we used serverspec and later moved to [testinfra](https://testinfra.readthedocs.io).  Testinfra has quite a few backends, one of which supports [kubectl](https://testinfra.readthedocs.io/en/latest/backends.html#kubectl).

I was thinking a kubectl resource might be useful.  This would allow us to look at the deployed state and assert things are the way we expect.

Thanks for the great tool!  Let me know what you think.

**Comment by aelsabbahy** [comment]
I'm unclear on this. Is this a request for supporting testing instances running in k8s or a request for testing a k8s cluster using kubectl?

**Comment by retr0h** [comment]
the latter

**Comment by aelsabbahy** [comment]
Gotcha, this is out of scope for Goss for two reasons:
1. It seem to be more about testing remote state rather than local (it can be local.. but not necessarily.
2. It's not really a core OS feature that is shared amongst majority of users, but rather an application (k8s in this case).

In the past I've rejected docker support tickets (e.g. #18)

I've documented a general guideline for what is considered in scope for Goss vs out of scope and user can just use `command` to handle:
https://github.com/aelsabbahy/goss/blob/master/.github/CONTRIBUTING.md#feature-requests

Please let me know if you have any questions.

**Comment by aelsabbahy** [comment]
Closing this as I'm trying to get the open issues back under control.

If you feel this hasn't been addressed feel free to reopen.

Thank you for using Goss and providing feedback/requests!

**Comment by aelsabbahy** [comment]
For what it's worth I was asking since someone recently added [kgoss](https://github.com/aelsabbahy/goss/blob/master/extras/kgoss/README.md)
