### ISSUE TITLE
/goss $ INFO: Deleting container

### ISSUE THREAD

**Issue by SrujanRajDev** [aelsabbahy/goss#417]
Am trying run dgoss on a Docker image(test-1) but it's giving me a following error:

$ dgoss edit test-1

INFO: Starting docker container
INFO: Container ID: c26cec71
INFO: Run goss add/autoadd to add resources
/goss $ INFO: Deleting container

I want to understand why it is exiting from interactive shell and deleting the container.  Please help !!

**Comment by richnusgeeks** [comment]
The similar was happening to me and it was due to the container ENTRYPOINT/CMD process exiting. Try to run your container independently through _docker run_ and dump its log through _docker logs_ to figure out what is causing the ENTRYPOINT/CMD process to exit.

Another straight way without docker run/logs is: generate a dummy goss.yaml through _goss a port 80_ and then running dgoss with some delay through _GOSS_SLEEP=10 dgoss run test-1_ to dump your container's log directly.

I hope it helps.

**Comment by aelsabbahy** [comment]
@SrujanRajDev did you ever figure this out?

**Comment by croensch** [comment]
Does this mean i can't test a container that does not have a long-running process?

**Comment by aelsabbahy** [comment]
You can just keep the container running with a command, tail, sleep, shell with a tty.

Example:
```
 dgoss run -t centos:7 sh

# or
dgoss run centos:7 tail -f /dev/null
```

some more examples are here:
https://github.com/docker/compose/issues/1926
