### ISSUE TITLE
Native support for REST tests (feature request)

### ISSUE THREAD

**Issue by sshipway** [aelsabbahy/goss#484]
Can we add REST tests as a native check type?  Not sure how this should be done, but maybe with parameters has to go in and a list of tests of outputfield-compare-value tests.  This would remove the need for complex wget|jq command definitions to perform this sort of API tests.

**Comment by aelsabbahy** [comment]
Feel free to create a new focused feature request ticket bases on our chat here:
https://github.com/aelsabbahy/goss/issues/375#issuecomment-564853916

For jq type stuff, I was thinking of eventually adding a jmespath matcher. The one challenge currently is io.readers are handled differently than everything else in Goss and that would need to be addressed prior to jmespath matcher being useful.

**Comment by aelsabbahy** [comment]
Since this is the best named story, I'll make this the official story to track this.

As per my comment here: https://github.com/aelsabbahy/goss/issues/375#issuecomment-564853916

Adding the `method`, `request-body`, and `url` seems like a useful enhancement.

This is approved for anyone that would like to work on this. If there are further changes, we can discuss it further here.

**Comment by aelsabbahy** [comment]
I think this might was closed  by #647

Please let me know if it's not.
