### ISSUE TITLE
Discussion: Multi-OS support

### ISSUE THREAD

**Issue by aelsabbahy** [aelsabbahy/goss#551]
Those who have followed the project know that I'm very hesitant to add support for other OSs in goss. This ticket is to discuss some of the challenges that need to be solved prior to dedicating time/resources to this endeavor: 

1. Locally testing and reproducing bugs - Currently any goss feature/test can be reproduced on a Linux, OSX, and windows machine through docker. What would be the path to locally test/reproduce features locally for Windows and OSX?

2. Similar to 1 above. Currently, due to docker providing a reproducible test environment, it is very easy to implement CI for goss in travis or other CI engines so long as they support docker. What would be the path to provide isolated/reproducible tests Windows and OSX?

3. Some concepts in goss don't translate well for windows/OSX. For example, package managers. Goss assumes one package manager per distribution. Windows and OSX are a bit different when it comes to this. For example, windows has packages that can be queried through powershell, but also has a bunch of 3rd party package managers (eg. chocholaty, scoop, appget.). OSX has appstore (not sure how to query this on the CLI or if it's even worthwhile), but then there's macports/brew/nix. What will be the criteria that determines what will be supported by goss and what won't be? Regardless of choice, #539 would have to be completed first. 

4. Given that I currently do not have an interest in maintaining Windows and OSX support, how will this effort continue to be maintained? If maintainers will step up and own parts of the code, what happens when they inevitably move on? Would windows/OSX just be unsupported versions of goss?

5. ROI... I assume Goss on Linux will naturally attract both greater interest as well as support from the open-source community. Is Goss useful for OSX given that it's not a common server platform? For windows, how likely are windows sysadmins to use Goss. Does the concept of a YAML-based, CLI system testing tool make sense inside of a Microsoft ecosystem?

**Comment by directionless** [comment]
👋 I do various multiplatform things. I'm currently evaluating different serverspec style tools to as part of a package building pipeline. I found `goss`, and the small nature of it appealing. But, windows and osx support are pretty key. Some rambling...

> I'm wondering if it makes sense to split Goss up into multiple distributions/projects with different maintainers (from #411)

I think this is undesirable. It makes things much less simple.

> Locally testing and reproducing bugs

I think that's a hard, if not impossible, problem. While there are some VM answers, they're cumbersome. It's not ideal, but I've taken the approach of trying to have well tested pieces (if not existing cross platform go libraries), and building on them. I don't worry much about daily work on windows, I spin that up as needed. 

> implement CI for goss

There are mac and windows CI options. Similar to the local testing, this may not be critical. But, I believe travis, Azure, and circleci all have options here. (I don't much use travis anymore, it seems pretty moribund)

> Given that I currently do not have an interest in maintaining Windows and OSX support, how will this effort continue to be maintained

That seems harder. goss looks like a small project, with a single busy maintainer. Either it has some less loved parts, or it gets bigger. (https://github.com/aelsabbahy/goss/issues/411)

> Goss useful for OSX given that it's not a common server platform? For windows, how likely are windows sysadmins to use Goss. Does the concept of a YAML-based, CLI system testing tool make sense inside of a Microsoft ecosystem?

That seems like a narrow view of what it's useful for. As mentioned, I'm looking to test package behaviors. 

> Some concepts in goss don't translate well for windows/OSX. For example, package managers. Goss assumes one package manager per distribution

I think this is the core of it. But, I don't know that it needs to be perfect. I think it depends on where the project goes. I could imagine a framework where not all drivers are supported on all OSes. 

*  Things like  `process` & `file` is based on an underlying library that already has cross platform support. Those are easy.
* `service` is a really tricky question. I think it has a pretty clear meaning on windows, but I think on linux it's much less clear. I didn't trace through the code to see how that's determined, but it seems fraught.
* Similar, `package`. While there are only a couple common packaging systems, there's a lot of complexity in the weeds. 

Another route here, would be to use osquery. This was discussed a bit in https://github.com/aelsabbahy/goss/issues/198

**Comment by aelsabbahy** [comment]
Wonder if it would be best to just rely 90-100% on unit tests for Windows/OSX?

> That seems like a narrow view of what it's useful for. As mentioned, I'm looking to test package behaviors.

Can you expand on this or provide some examples of this use case?

**Comment by directionless** [comment]
>>That seems like a narrow view of what it's useful for. As mentioned, I'm looking to test package behaviors.
>>
> Can you expand on this or provide some examples of this use case?

Sure! I was saying I thought testing servers was narrow. Specifically the server part. One of the big shifts I've seen in the last several years, is that endpoint management has adopted more and more configuration management tools. There's clear space to help with any kind of verification and testing of that.

As said, I'm currently looking to test packaging builds. For me, this is basically targeting laptops. Did this `msi` put the files where I wanted?  Did the rpm install a systemd file that correctly tried to start a service? The the `pkg` install? Are they detected as code signed?

I generally think of `goss` in the same category as inspec and serverspec. Some use cases I've seen for those tools that are often server oriented, but not inherently. Another one, mostly from `inspec` is compliance oriented testing.

**Comment by pedroMMM** [comment]
For `1` and `2`, a solid unit test coverage in conjuncture with a CI Integration Test step that targets all supported OSs (with the ability to run them locally if the OS matches) should suffice. The ability to spin up an annoying VM is aways around to debug complex bugs. 

`3` If a concept doesn't translate well then simply don't implement it and evaluate the user requests.

`4` Allow the interested contributors to add the other OSs support under some kind of "preview" mode. I am not fully convinced that the code changes will be drastic. If these changes aren't too vast the upkeep should be minimal by relying on the CI Integration Testing.

`5` I agree with @directionless that there are many more uses for Goss that just testing servers. Even testing servers is a wide topic that can go into compliance testing very easily.

**Comment by petemounce** [comment]
> 1. Locally testing and reproducing bugs - Currently any goss feature/test can be reproduced on a Linux, OSX, and windows machine through docker. What would be the path to locally test/reproduce features locally for Windows and OSX?

travis supports both platforms; while that's not ideal, it's probably fine for a gate initially.

It's quite likely that people wanting support for Windows and OSX will have those platforms, at which point the problem is limited to just having a working golang toolchain installed, which is an installer package for either platform.

On macOS, within our internal CI, we're starting to use Anka, which is a container-analogue for macOS that looks promising. It's sadly not OSS or I'd suggest it.

> 2. Similar to 1 above. Currently, due to docker providing a reproducible test environment, it is very easy to implement CI for goss in travis or other CI engines so long as they support docker. What would be the path to provide isolated/reproducible tests Windows and OSX?

I'd be satisfied with travis' Windows and OSX support; it provides clean enough instances per job IMO, and I'd be comfortable executing integration tests directly on the reproducible-enough host, there.

> 3. Some concepts in goss don't translate well for windows/OSX.

I'm _personally_ not so invested in the `package` assertion being cross-platform implemented - as in, it would be nice, but I can work around it via `command` very readily. Usually, I want to know that a binary is present on `PATH` and it doesn't matter as much to me _how_ it got there. (Others' mileage may clearly vary)

The ones besides package-managers that stand out for me are
* `file`: logically the same file can exist at different paths on different platforms; it would be advantageous to make the `file` key be a name, and introduce a `paths` dictionary to the assertion keyed on platform name to allow the same file content to be asserted against at a platform-specific location. Similar to how `command` now has an `exec` attribute that is the _actual_ command to assert against.
* `file`: there's different symlink logic going to be required on Windows - but many people on Windows tend to not use symlinks.
* `file`: mode/user/group are not a thing on Windows, but Windows instead has a very expressive ACL system. (some might say too expressive...)
* `service`: would need `launchd` and `windows service manager` implementations
* `group`: would be a different implementation on Windows (`net localgroup ...` or the newer powershell cmdlets)
* `interface`: would probably not work without changes on Windows.
* `mount`: would have Windows-specific semantics as Windows filesystems are volume centric
* `user`: would be a different implementation on Windows (`net user ...` or the newer powershell cmdlets)

> 4. [maintenance]

At improbable, we're willing to chip in some support and maintenance; we depend on goss cross-platform. We use it for
* local workstation drift detection
* CI drift detection (and, more recently, automatically killing agents that drift)

> 5. [ROI]

goss is useful for both. I'd argue _more_ so Windows and OSX because those platforms
* have by comparison a more difficult configuration-management experience
* (Windows) fewer people that are command-line first

so being able to make machine assertions is _more_ valuable because the chance of drift is way higher.

**Comment by aelsabbahy** [comment]
How does this sound as a game plan?

1. Create $Resource_$OS.go files to open the door for other OS support in the future. (This can be started now)
2. Create a ticket for each resource/os combination or one for OS where we can agree on syntax for that particular resource and possible dependency changes.
3. For Windows/osx unit tests will be required, maybe a smoke test in CI can be added too as a bonus.
4. Documentation changes required to mention the "beta" nature of multi-os initially.

**Comment by aelsabbahy** [comment]
> file: logically the same file can exist at different paths on different platforms; it would be advantageous to make the file key be a name, and introduce a paths dictionary to the assertion keyed on platform name to allow the same file content to be asserted against at a platform-specific location. Similar to how command now has an exec attribute that is the actual command to assert against.

@petemounce I'd like to discuss this further maybe in a ticket from item 2 above.

**Comment by aelsabbahy** [comment]
Also, as a side.. potentially related note. There's a batch of changes scheduled that will hopefully be major enhancements to both the templating and matching logic.

Trying to balance those and new OS support.

**Comment by aelsabbahy** [comment]
@petemounce 

To make progress on this, and since you guys at improbable have already made progress on this.

How does this sound?
1. Close out all existing multi-os tickets.
2. Create _linux.go files and add notimplented errors
3. Add windows/osx update document with table that shows what's supported where. (Have unit tests with this)
4. See what the next steps are from there

**Comment by petemounce** [comment]
Sorry for taking a while to respond. Crazy world. Thank you for chasing, and progressing!

I think those steps are very workable.

I think renaming files to _linux.go is unnecessary; I think it will be less effort overall to introduce _windows.go and _darwin.go only where needed. Based on our (caveat: not exhaustive) trials, many things work fine.

I think a matrix is a great idea. I propose 2 columns per OS, one each for implemented-with-unit coverage and with integration coverage. Maybe one more for tracking issue? The more granular, the more likely contributions will drive by.

I'll open a PR to add the changes we made to enable the binaries to be output from CI tomorrow, and document those as alpha. Does that sound alright?

**Comment by aelsabbahy** [comment]
Yeah, that sounds great. I would like a table in the documentation for what's supported for each platform.

> I think renaming files to _linux.go is unnecessary

I just meant for things that aren't cross-platform. Otherwise, what happens when yaml contains an unsupported test for that platform?

I have a lot of changes that in excited for going into the 0.4.0 release, maybe initial multi-OS can be part of it.

**Comment by petemounce** [comment]
> I just meant for things that aren't cross-platform. Otherwise, what happens when yaml contains an unsupported test for that platform?

Gotcha, ok.
