### ISSUE TITLE
ssh and exec support

### ISSUE THREAD

**Issue by stephanbuys** [aelsabbahy/goss#6]
Hi,

Cool project, any strategies for remote scanning (using ssh), like serverspec? Also, can you support something that can exec an arbitrary command or script?

Regards,
Stephan

**Comment by aelsabbahy** [comment]
**remote-scanning:**
There is no remote execute scanning built in currently, mostly because goss for the most part doesn't rely on external commands, so there are no commands to send over ssh. This is how goss runs so fast.

However, since goss reads from stdin, you could do something like this:
```bash
cat goss.json | ssh remote-host 'goss validate'
```

I'm hesitant to add a remote execution feature that copies the goss binary and json to a tmp location on the remote host and runs it from there, since it would take away from the tools simplicity and is something that can be done in a few lines of shell.

**arbitrary command:**
Adding an arbitrary command is already supported:
```bash
$ goss add command 'java -version'
Adding Command to './goss.json':

{
    "java -version": {
        "exit-status": "0",
        "stdout": [],
        "stderr": [
            "java version \"1.7.0_79\"",
            "OpenJDK Runtime Environment (fedora-2.5.5.0.fc20-x86_64 u79-b14)",
            "OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)"
        ]
    }
}
```

**Comment by aelsabbahy** [comment]
Closing, let me know if you have other questions and I'll reopen.

**Comment by q2dg** [comment]
Maybe https://github.com/teuton-software/teuton can help
