### ISSUE TITLE
dgoss: commented out vars injections are not ignored in yaml gossfile

### ISSUE THREAD

**Issue by lucasmurphey** [aelsabbahy/goss#613]
Using goss v0.3.13 and latest dgoss
Commenting out sections of a gossfile is problematic when using injected vars as they are not being ignored:

```yaml 
package:
  tomcat:
    installed: true
#    versions:
#      - {{ .Vars.TOMCAT_VERSION }}
```
```
INFO: Starting docker container
INFO: Container ID: 96793649
INFO: Sleeping for 0.2
INFO: Container health
INFO: Running Tests
2020/09/10 10:08:15 template: test:5:16: executing "test" at <.Vars.TOMCAT_VERSION>: map has no entry for key "TOMCAT_VERSION"
INFO: Deleting container
```

Removing the commented line with the var obviously resolves the issue:
```yaml 
package:
  tomcat:
    installed: true
#    versions:
#      - not_a_var
```
```
INFO: Starting docker container
INFO: Container ID: 06ca315f
INFO: Sleeping for 0.2
INFO: Container health
INFO: Running Tests
Package: tomcat: installed: matches expectation: [true]


Total Duration: 0.063s
Count: 1, Failed: 0, Skipped: 0
INFO: Deleting container
```

**Comment by aelsabbahy** [comment]
I'm not sure this is really a bug, the file is rendered using [text/template](https://golang.org/pkg/text/template/) first, then processed as YAML.

You can escape golang's text/template, using the following if you like (or something similar):
```
{{ `{{ .Vars.TOMCAT_VERSION }}` }}
```

I'm not sure it would be possible to detect what will end up as a YAML comment without first rendering the template due to the way YAML works with multi-line strings, for example:
```yaml
    my_story: |
        Line 1
        Line 2
        # Hash line containing tomcat version: {{ .Vars.TOMCAT_VERSION }}
```
