### ISSUE TITLE
mount  option is not working as expected

### ISSUE THREAD

**Issue by vinodhkumart** [aelsabbahy/goss#648]
/dev/mapper/testvg-home  /home xfs defaults,nosuid 0 0 is my fstab entry. I wrote my goss test as below.

mount:
  /home:
    exists: true
    opts:
    - defaults
    - nosuid
    source: /dev/mapper/testvg-home
    filesystem: xfs

When i run the test it says the below error. Looks like it takes the hardcoded opts of  rw, relatime by default. How can i exclude this ?
 Test:
----------
Failures/Skipped:

Mount: /home: opts:
Expected
    <[]string | len:3, cap:3>: ["rw", "nosuid", "relatime"]
to contain element matching
    <string>: defaults

Total Duration: 0.001s
Count: 4, Failed: 1, Skipped: 0

**Comment by aelsabbahy** [comment]
I *think* this is related to https://github.com/aelsabbahy/goss/issues/443 which is scheduled to be released with v0.4.0

Can you look over the other PR and verify if it is the same issue?

**Comment by vinodhkumart** [comment]
Yes, The same issue for me also. Thanks for the reply

**Comment by wilrodriguez** [comment]
@aelsabbahy I don't think this is anything wrong with goss, so it's not going to be fixed by that release.

I think it has more to do with the fact that `defaults` is an alias to the system defaults and not a representation of what the actual mount options are for a mounted filesystem. It is only relevant to the mount command and fstab and is equivalent to `rw`, `suid`, `dev`, `exec`, `auto`, `nouser`, and `async` (note that the exact list may change based on your platform). It would make sense to test for defaults if you were testing an fstab entry's mount options, as that's the only place where the defaults alias exists, but goss currently can't do that, it only tests live mounts. Instead, you'll want to only test the options you care about, such as nosuid.

**Comment by aelsabbahy** [comment]
@wilrodriguez Good point regarding aliases.

I would be curious on what `/proc/self/mountinfo` looks like for you @vinodhkumart

**Comment by vinodhkumart** [comment]
Thanks for the info @wilrodriguez 

@aelsabbahy Sample output for home directory under the /proc/self/mountinfo is as follows.

46 39 253:2 / /home rw,nosuid,relatime shared:31 - xfs /dev/mapper/testvg-homelv  rw,attr2,inode64,noquota
